{
 "title": "First Dashboard For Cloud Event Processing Platform",
 "time": { "from": "2026-03-07T00:13:57.722Z", "to": "2026-03-07T00:19:15.375Z" },
 "panels": [
  {
   "title": "Total requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(flask_http_request_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(flask_http_request_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (path) (flask_http_request_duration_seconds_count)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(flask_http_request_duration_seconds_sum[1m]))\r\n/\r\nsum by (path) (rate(flask_http_request_duration_seconds_count[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}