apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      containers:
        - name: events-api
          image: events-api:kubernetes
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://app:apppassword@postgres-postgresql:5432/events"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3