apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: events-api-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: events-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s